### ISSUE TITLE
Iteration 1 (one week): Web site data analysis, data adquisition, simple statistical processing.

### ISSUE THREAD

**Issue by DRTorresRuiz** [BigData2020MasterInformatica/FinanceAnalysis#4]
Describe what you have done this week in this `documentation` issue. Cheers

**Comment by FernandoGD97** [comment]
Daniel and I have been researching the different sources of information. I have focused on the YFinance library. I have documented the use of the API, both its installation and the different attributes that we can obtain with it. Also, I have automated it so that from a series of inputs (company ticket, start date and end date), the dataset is generated and a pre-processing is done, replacing the unknown values by the arithmetic mean. Finally, I have represented the distribution of the dataset attributes.

**Comment by DRTorresRuiz** [comment]
We both, Fernando and I, have analysed how different sources of financial data work. My work contribution is included in #6. There are two APIs commented:

1. [TradingEconomics](https://github.com/tradingeconomics/tradingeconomics/tree/master/python).
2. [Financial Modeling Prep API](https://financialmodelingprep.com/developer/docs/)

The first one does not seem to be free, but provides a limited demo. The second one, however, has some options that require to be a premium user, but most of the functionalities are free. 

Another aspect to consider is the format of the requested data, TradingEconomics can return data in either JSON or Dataframe format data. Nonetheless, we need to make an HTTPS Request and it only returns data in a JSON format - or so we have seen. This means the first one is more limited, but it would be easier to work with. In order to use the second one, we would have to create a custom receiver to work with an https client as [this user suggests](https://stackoverflow.com/a/30677890). 

Additionally, we would like to share with all the links below that could be fairly helpful in the next steps:

- https://towardsdatascience.com/deep-learning-in-finance-is-this-the-future-of-the-financial-industry-a29b561031e9
- https://towardsdatascience.com/machine-learning-in-finance-why-what-how-d524a2357b56
- https://towardsdatascience.com/deep-learning-in-finance-9e088cb17c03
- https://towardsdatascience.com/applying-two-ideas-from-advances-in-financial-machine-learning-433c7950858a
- https://databricks.com/blog/2020/01/27/time-series-forecasting-prophet-spark.html
- https://databricks.com/blog/2019/10/09/democratizing-financial-time-series-analysis-with-databricks.html

and several videos:

- https://www.infoq.com/presentations/spark-financial-modeling/
- https://www.youtube.com/watch?v=wLJi8YQcWjc

**Comment by mchuckles** [comment]
Benjamin and I have been researching on the classification task. We implemented the Linear Regression model that was trained with the data from a .txt file. Besides that, I tried to find on Kaggle a bigger dataset for us to train and test our algorithm. 
Links used for research:
- https://towardsdatascience.com/building-a-linear-regression-with-pyspark-and-mllib-d065c3ba246a
- https://spark.apache.org/docs/latest/ml-classification-regression.html

**Comment by benjivega** [comment]
Iuliana and I have been looking for regression classification models. The first model was a basic model, a linear regression model. Then we were looking over the commonly used models and we found Gradient Boosting Regressor. We were testing this model using simple data and comparing it with Linear Regression.

- https://towardsdatascience.com/building-a-linear-regression-with-pyspark-and-mllib-d065c3ba246a
- https://github.com/scorpionhiccup/StockPricePrediction/blob/master/Documents/StockPricePrediction.pdfhttps://spark.apache.org/docs/latest/ml-classification-regression.html

**Comment by chachir** [comment]
I made a simple script for clustering. In this script, there are two classes of models: k-means and a hybrid one called bisecting k-means. As my fellows, these models have been tested with simple data found in the CV. Not only did I contributed with the clustering models but I've been researching more datasets in order to test the models with more complex data as well.

- https://www.bmc.com/blogs/python-spark-k-means-example/

- https://runawayhorse001.github.io/LearningApacheSpark/clustering.html

**Comment by leticiayepezchavez** [comment]
Jose and I have been working in the following items:

- Investigation and analyze of the Finnhub API. For this we have uploaded to the repository a notebook with some samples.
- Extract streaming data from Finnhub(Websocket) througth two scripts:
   1. Script to get data from Finnhub Api and save inside a CSV file with the columns: name, money and time.
   2. Script to read the finance data in spark streaming from a directory which contains CSV Files. This data is loaded with time window inside a dataframe.

- [https://finnhub.io/docs/api]
